//
//  SnapshotHelper.swift
//  CryptoPortfolioUITests
//
//  Created by Donnadony Mollo on 01/02/26.
//
//  This file is auto-generated by fastlane snapshot.
//  For more information, visit: https://docs.fastlane.tools/actions/snapshot/
//

import Foundation
import XCTest

var deviceLanguage = ""
var locale = ""

func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {
    Snapshot.setupSnapshot(app, waitForAnimations: waitForAnimations)
}

func snapshot(_ name: String, timeWaitingForIdle timeout: TimeInterval = 20) {
    Snapshot.snapshot(name, timeWaitingForIdle: timeout)
}

enum SnapshotError: Error, CustomDebugStringConvertible {
    case cannotFindHomeDirectory
    case cannotFindSimulatorHomeDirectory
    case cannotAccessSimulatorHomeDirectory(String)
    case cannotRunOnPhysicalDevice

    var debugDescription: String {
        switch self {
        case .cannotFindHomeDirectory:
            return "Couldn't find Snapshot configuration files - can't find current home directory"
        case .cannotFindSimulatorHomeDirectory:
            return "Couldn't find Snapshot configuration files - can't find simulator home directory"
        case .cannotAccessSimulatorHomeDirectory(let simulatorHomeDirectory):
            return "Couldn't find Snapshot configuration files - can't access simulator home directory at \(simulatorHomeDirectory)"
        case .cannotRunOnPhysicalDevice:
            return "Can't run on physical device"
        }
    }
}

@objcMembers
open class Snapshot: NSObject {
    static var app: XCUIApplication?
    static var waitForAnimations = true
    static var cacheDirectory: URL?
    static var screenshotsDirectory: URL? {
        return cacheDirectory?.appendingPathComponent("screenshots", isDirectory: true)
    }
    static var deviceLanguage: String?
    static var currentLocale: String?

    open class func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {

        Snapshot.app = app
        Snapshot.waitForAnimations = waitForAnimations

        do {
            let cacheDir = try pathPrefix()
            Snapshot.cacheDirectory = cacheDir
            Snapshot.deviceLanguage = deviceLanguage
            Snapshot.currentLocale = locale
        } catch let error {
            print(error)
        }
    }

    class func snapshot(_ name: String, timeWaitingForIdle timeout: TimeInterval = 20) {
        if timeout > 0 {
            waitForLoadingIndicatorToDisappear(within: timeout)
        }

        print("snapshot: \(name)") // more information about this, check out https://docs.fastlane.tools/actions/snapshot/#how-does-it-work

        if Snapshot.waitForAnimations {
            sleep(1) // Waiting for the animation to be finished (kind of)
        }

        #if os(visionOS)
        let screenshot = XCUIScreen.main.screenshot()
        #elseif os(iOS)
        let screenshot = app?.windows.firstMatch.screenshot()
        #elseif os(tvOS)
        let screenshot = app?.windows.firstMatch.screenshot()
        #elseif os(macOS)
        let screenshot = app?.windows.firstMatch.screenshot()
        #elseif os(watchOS)
        let screenshot = app?.screenshot()
        #endif

        guard let screenshotsDirectory = screenshotsDirectory else {
            print("Couldn't detect/set screenshots directory")
            return
        }

        do {
            try FileManager.default.createDirectory(at: screenshotsDirectory, withIntermediateDirectories: true, attributes: nil)
        } catch {
            print("Couldn't create screenshots directory")
            return
        }

        let language = Snapshot.deviceLanguage
        let locale = Snapshot.currentLocale

        do {
            let path = screenshotsDirectory.appendingPathComponent("\(language)-\(locale)-\(name).png")
            guard let screenshot = screenshot else {
                print("Couldn't capture screenshot")
                return
            }
            try screenshot.pngRepresentation.write(to: path)
        } catch let error {
            print("Problem writing screenshot: \(name) to \(screenshotsDirectory)/\(language)-\(locale)-\(name).png")
            print(error)
        }
    }

    class func waitForLoadingIndicatorToDisappear(within timeout: TimeInterval) {
        #if os(tvOS)
            return
        #endif

        let networkLoadingIndicator = XCUIApplication().otherElements.deviceStatusIndicators.networkLoadingIndicators.firstMatch
        let networkLoadingIndicatorDisappeared = XCTNSPredicateExpectation(predicate: NSPredicate(format: "exists == false"), object: networkLoadingIndicator)
        _ = XCTWaiter.wait(for: [networkLoadingIndicatorDisappeared], timeout: timeout)
    }

    class func pathPrefix() throws -> URL? {
        let homeDir: URL
        // on macOS it's /Users/<username>/Library
        // and on iOS/tvOS/visionOS it's a unique path for each app
        #if os(iOS) || os(tvOS) || os(visionOS)
        guard let simulatorHostHome = ProcessInfo().environment["SIMULATOR_HOST_HOME"] else {
            throw SnapshotError.cannotFindSimulatorHomeDirectory
        }
        guard let homeDirUrl = URL(string: simulatorHostHome) else {
            throw SnapshotError.cannotAccessSimulatorHomeDirectory(simulatorHostHome)
        }
        homeDir = URL(fileURLWithPath: homeDirUrl.path)
        #elseif os(macOS)
        guard let user = ProcessInfo().environment["USER"] else {
            throw SnapshotError.cannotFindHomeDirectory
        }
        guard let homeDirUrl = URL(string: "/Users/\(user)") else {
            throw SnapshotError.cannotFindHomeDirectory
        }
        homeDir = URL(fileURLWithPath: homeDirUrl.path)
        #else
        throw SnapshotError.cannotRunOnPhysicalDevice
        #endif
        return homeDir.appendingPathComponent("Library/Caches/tools.fastlane")
    }
}

private extension XCUIElementAttributes {
    var isNetworkLoadingIndicator: Bool {
        if hasAllowListedIdentifier { return false }
        let hasOldLoadingIndicatorSize = frame.size == CGSize(width: 10, height: 20)
        let hasNewLoadingIndicatorSize = frame.size.width.isBetween(46, and: 47) && frame.size.height.isBetween(2, and: 3)
        return hasOldLoadingIndicatorSize || hasNewLoadingIndicatorSize
    }

    var hasAllowListedIdentifier: Bool {
        let allowListedIdentifiers = ["GeofenceLocationTrackingOn", "StandardLocationTrackingOn"]
        return allowListedIdentifiers.contains(identifier)
    }

    func isStatusBar(_ deviceWidth: CGFloat) -> Bool {
        if elementType == .statusBar { return true }
        guard frame.origin == .zero else { return false }
        let oldStatusBarSize = CGSize(width: deviceWidth, height: 20)
        let newStatusBarSize = CGSize(width: deviceWidth, height: 44)
        return [oldStatusBarSize, newStatusBarSize].contains(frame.size)
    }
}

private extension XCUIElementQuery {
    var networkLoadingIndicators: XCUIElementQuery {
        let isNetworkLoadingIndicator = NSPredicate { (evaluatedObject, _) in
            guard let element = evaluatedObject as? XCUIElementAttributes else { return false }
            return element.isNetworkLoadingIndicator
        }
        return self.containing(isNetworkLoadingIndicator)
    }

    var deviceStatusIndicators: XCUIElementQuery {
        let deviceWidth = XCUIApplication().windows.firstMatch.frame.width

        let isStatusBar = NSPredicate { (evaluatedObject, _) in
            guard let element = evaluatedObject as? XCUIElementAttributes else { return false }
            return element.isStatusBar(deviceWidth)
        }
        return self.containing(isStatusBar)
    }
}

private extension CGFloat {
    func isBetween(_ numberA: CGFloat, and numberB: CGFloat) -> Bool {
        return numberA...numberB ~= self
    }
}

// Please don't remove the lines below
// They are used to detect outdated configuration files
// SnapshotHelperVersion [1.30]